{
    "status": 500,
    "error": "Internal Server Error",
    "exception": "#<NameError: uninitialized constant ApplicationController::JwToken>",
    "traces": {
        "Application Trace": [
            {
                "exception_object_id": 17120,
                "id": 0,
                "trace": "app/controllers/application_controller.rb:2:in `<class:ApplicationController>'"
            },
            {
                "exception_object_id": 17120,
                "id": 1,
                "trace": "app/controllers/application_controller.rb:1:in `<main>'"
            },
            {
                "exception_object_id": 17120,
                "id": 5,
                "trace": "app/controllers/users_controller.rb:1:in `<main>'"
            }
        ],
        "Framework Trace": [
            {
                "exception_object_id": 17120,
                "id": 2,
                "trace": "bootsnap (1.16.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'"
            },
            {
                "exception_object_id": 17120,
                "id": 3,
                "trace": "bootsnap (1.16.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'"
            },
            {
                "exception_object_id": 17120,
                "id": 4,
                "trace": "zeitwerk (2.6.6) lib/zeitwerk/kernel.rb:30:in `require'"
            },
            {
                "exception_object_id": 17120,
                "id": 6,
                "trace": "bootsnap (1.16.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'"
            },
            {
                "exception_object_id": 17120,
                "id": 7,
                "trace": "bootsnap (1.16.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'"
            },
            {
                "exception_object_id": 17120,
                "id": 8,
                "trace": "zeitwerk (2.6.6) lib/zeitwerk/kernel.rb:30:in `require'"
            },
            {
                "exception_object_id": 17120,
                "id": 9,
                "trace": "activesupport (7.0.4.2) lib/active_support/inflector/methods.rb:280:in `const_get'"
            },
            {
                "exception_object_id": 17120,
                "id": 10,
                "trace": "activesupport (7.0.4.2) lib/active_support/inflector/methods.rb:280:in `constantize'"
            },
            {
                "exception_object_id": 17120,
                "id": 11,
                "trace": "activesupport (7.0.4.2) lib/active_support/core_ext/string/inflections.rb:74:in `constantize'"
            },
            {
                "exception_object_id": 17120,
                "id": 12,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/http/request.rb:90:in `controller_class_for'"
            },
            {
                "exception_object_id": 17120,
                "id": 13,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/request/utils.rb:95:in `action_encoding_template'"
            },
            {
                "exception_object_id": 17120,
                "id": 14,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/request/utils.rb:83:in `encode'"
            },
            {
                "exception_object_id": 17120,
                "id": 15,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/request/utils.rb:45:in `set_binary_encoding'"
            },
            {
                "exception_object_id": 17120,
                "id": 16,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/http/parameters.rb:68:in `path_parameters='"
            },
            {
                "exception_object_id": 17120,
                "id": 17,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:48:in `block in serve'"
            },
            {
                "exception_object_id": 17120,
                "id": 18,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:32:in `each'"
            },
            {
                "exception_object_id": 17120,
                "id": 19,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:32:in `serve'"
            },
            {
                "exception_object_id": 17120,
                "id": 20,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:852:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 21,
                "trace": "rack (2.2.6.2) lib/rack/etag.rb:27:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 22,
                "trace": "rack (2.2.6.2) lib/rack/conditional_get.rb:27:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 23,
                "trace": "rack (2.2.6.2) lib/rack/head.rb:12:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 24,
                "trace": "activerecord (7.0.4.2) lib/active_record/migration.rb:603:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 25,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'"
            },
            {
                "exception_object_id": 17120,
                "id": 26,
                "trace": "activesupport (7.0.4.2) lib/active_support/callbacks.rb:99:in `run_callbacks'"
            },
            {
                "exception_object_id": 17120,
                "id": 27,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 28,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 29,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 30,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 31,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 32,
                "trace": "railties (7.0.4.2) lib/rails/rack/logger.rb:40:in `call_app'"
            },
            {
                "exception_object_id": 17120,
                "id": 33,
                "trace": "railties (7.0.4.2) lib/rails/rack/logger.rb:25:in `block in call'"
            },
            {
                "exception_object_id": 17120,
                "id": 34,
                "trace": "activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'"
            },
            {
                "exception_object_id": 17120,
                "id": 35,
                "trace": "activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:37:in `tagged'"
            },
            {
                "exception_object_id": 17120,
                "id": 36,
                "trace": "activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `tagged'"
            },
            {
                "exception_object_id": 17120,
                "id": 37,
                "trace": "railties (7.0.4.2) lib/rails/rack/logger.rb:25:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 38,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 39,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 40,
                "trace": "rack (2.2.6.2) lib/rack/runtime.rb:22:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 41,
                "trace": "activesupport (7.0.4.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 42,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'"
            },
            {
                "exception_object_id": 17120,
                "id": 43,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'"
            },
            {
                "exception_object_id": 17120,
                "id": 44,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:60:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 45,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 46,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/static.rb:23:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 47,
                "trace": "rack (2.2.6.2) lib/rack/sendfile.rb:110:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 48,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 49,
                "trace": "railties (7.0.4.2) lib/rails/engine.rb:530:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 50,
                "trace": "puma (5.6.5) lib/puma/configuration.rb:252:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 51,
                "trace": "puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'"
            },
            {
                "exception_object_id": 17120,
                "id": 52,
                "trace": "puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'"
            },
            {
                "exception_object_id": 17120,
                "id": 53,
                "trace": "puma (5.6.5) lib/puma/request.rb:76:in `handle_request'"
            },
            {
                "exception_object_id": 17120,
                "id": 54,
                "trace": "puma (5.6.5) lib/puma/server.rb:443:in `process_client'"
            },
            {
                "exception_object_id": 17120,
                "id": 55,
                "trace": "puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'"
            }
        ],
        "Full Trace": [
            {
                "exception_object_id": 17120,
                "id": 0,
                "trace": "app/controllers/application_controller.rb:2:in `<class:ApplicationController>'"
            },
            {
                "exception_object_id": 17120,
                "id": 1,
                "trace": "app/controllers/application_controller.rb:1:in `<main>'"
            },
            {
                "exception_object_id": 17120,
                "id": 2,
                "trace": "bootsnap (1.16.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'"
            },
            {
                "exception_object_id": 17120,
                "id": 3,
                "trace": "bootsnap (1.16.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'"
            },
            {
                "exception_object_id": 17120,
                "id": 4,
                "trace": "zeitwerk (2.6.6) lib/zeitwerk/kernel.rb:30:in `require'"
            },
            {
                "exception_object_id": 17120,
                "id": 5,
                "trace": "app/controllers/users_controller.rb:1:in `<main>'"
            },
            {
                "exception_object_id": 17120,
                "id": 6,
                "trace": "bootsnap (1.16.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'"
            },
            {
                "exception_object_id": 17120,
                "id": 7,
                "trace": "bootsnap (1.16.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'"
            },
            {
                "exception_object_id": 17120,
                "id": 8,
                "trace": "zeitwerk (2.6.6) lib/zeitwerk/kernel.rb:30:in `require'"
            },
            {
                "exception_object_id": 17120,
                "id": 9,
                "trace": "activesupport (7.0.4.2) lib/active_support/inflector/methods.rb:280:in `const_get'"
            },
            {
                "exception_object_id": 17120,
                "id": 10,
                "trace": "activesupport (7.0.4.2) lib/active_support/inflector/methods.rb:280:in `constantize'"
            },
            {
                "exception_object_id": 17120,
                "id": 11,
                "trace": "activesupport (7.0.4.2) lib/active_support/core_ext/string/inflections.rb:74:in `constantize'"
            },
            {
                "exception_object_id": 17120,
                "id": 12,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/http/request.rb:90:in `controller_class_for'"
            },
            {
                "exception_object_id": 17120,
                "id": 13,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/request/utils.rb:95:in `action_encoding_template'"
            },
            {
                "exception_object_id": 17120,
                "id": 14,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/request/utils.rb:83:in `encode'"
            },
            {
                "exception_object_id": 17120,
                "id": 15,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/request/utils.rb:45:in `set_binary_encoding'"
            },
            {
                "exception_object_id": 17120,
                "id": 16,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/http/parameters.rb:68:in `path_parameters='"
            },
            {
                "exception_object_id": 17120,
                "id": 17,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:48:in `block in serve'"
            },
            {
                "exception_object_id": 17120,
                "id": 18,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:32:in `each'"
            },
            {
                "exception_object_id": 17120,
                "id": 19,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:32:in `serve'"
            },
            {
                "exception_object_id": 17120,
                "id": 20,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:852:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 21,
                "trace": "rack (2.2.6.2) lib/rack/etag.rb:27:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 22,
                "trace": "rack (2.2.6.2) lib/rack/conditional_get.rb:27:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 23,
                "trace": "rack (2.2.6.2) lib/rack/head.rb:12:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 24,
                "trace": "activerecord (7.0.4.2) lib/active_record/migration.rb:603:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 25,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'"
            },
            {
                "exception_object_id": 17120,
                "id": 26,
                "trace": "activesupport (7.0.4.2) lib/active_support/callbacks.rb:99:in `run_callbacks'"
            },
            {
                "exception_object_id": 17120,
                "id": 27,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 28,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 29,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 30,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 31,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 32,
                "trace": "railties (7.0.4.2) lib/rails/rack/logger.rb:40:in `call_app'"
            },
            {
                "exception_object_id": 17120,
                "id": 33,
                "trace": "railties (7.0.4.2) lib/rails/rack/logger.rb:25:in `block in call'"
            },
            {
                "exception_object_id": 17120,
                "id": 34,
                "trace": "activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'"
            },
            {
                "exception_object_id": 17120,
                "id": 35,
                "trace": "activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:37:in `tagged'"
            },
            {
                "exception_object_id": 17120,
                "id": 36,
                "trace": "activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `tagged'"
            },
            {
                "exception_object_id": 17120,
                "id": 37,
                "trace": "railties (7.0.4.2) lib/rails/rack/logger.rb:25:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 38,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 39,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 40,
                "trace": "rack (2.2.6.2) lib/rack/runtime.rb:22:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 41,
                "trace": "activesupport (7.0.4.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 42,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'"
            },
            {
                "exception_object_id": 17120,
                "id": 43,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'"
            },
            {
                "exception_object_id": 17120,
                "id": 44,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:60:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 45,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 46,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/static.rb:23:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 47,
                "trace": "rack (2.2.6.2) lib/rack/sendfile.rb:110:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 48,
                "trace": "actionpack (7.0.4.2) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 49,
                "trace": "railties (7.0.4.2) lib/rails/engine.rb:530:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 50,
                "trace": "puma (5.6.5) lib/puma/configuration.rb:252:in `call'"
            },
            {
                "exception_object_id": 17120,
                "id": 51,
                "trace": "puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'"
            },
            {
                "exception_object_id": 17120,
                "id": 52,
                "trace": "puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'"
            },
            {
                "exception_object_id": 17120,
                "id": 53,
                "trace": "puma (5.6.5) lib/puma/request.rb:76:in `handle_request'"
            },
            {
                "exception_object_id": 17120,
                "id": 54,
                "trace": "puma (5.6.5) lib/puma/server.rb:443:in `process_client'"
            },
            {
                "exception_object_id": 17120,
                "id": 55,
                "trace": "puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'"
            }
        ]
    }
}